a=int(input("Enter number 1:"))
b=int(input("Enter number 2:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulus:",a%b)
print("Floor Division:",a//b)
print("Exponent:",a**b)
